### ISSUE TITLE
Doc update for KVM

### ISSUE THREAD

**Issue by dr953** [perez987/Intel-UHD-Graphics-630-on-macOS#1]
Please, update the `iGPU as main card` section to state that if a Hackintosh is being installed in a QEMU virtual machine, the primary GPU in BIOS must be set to dGPU.

Otherwise, `vesafb` grabs the iGPU, which (due to a memory allocation conflict) results in a long delay on startup/shutdown and multi-gigabyte logs: BAR n: can't reserve...

If `vga=off` is added to `grub`, then the card is not claimed, however it also does not work (blank screen).

**Comment by perez987** [comment]
@dr953 
Sorry the delayed answer.
Thanks for your post.
If I understand well, when using macOS as VM in QEMU with iGPU as main or single card, iGPU must be set as primary card in BIOS. 
But this is the same as in native mode (no QEMU). You can read in the Readme file >> `iGPU as main card`>> **Enable it on the motherboard as main card: Initial Display Output IGFX instead of PCIe 1 Slot**. Do you think that this text isn't clear enough?

**Comment by dr953** [comment]
It is the opposite to that. When installing in QEMU, the iGPU must NOT be set as the main card. The dGPU must be set as the main card.

**Comment by perez987** [comment]
@dr953 
Ah! I have understood it just backwards. Thanks.
Do I add a note about it or do you prefer to write it yourself as a PR to the repository?

**Comment by dr953** [comment]
You can add a note

**Comment by perez987** [comment]
@dr953 
Done. Thanks.
